name: CI

on:
    pull_request:
 
jobs:
  security:
    name: Security
    uses: ./.github/workflows/security.yaml
    secrets: inherit
   
  build-maven:      
    name: build with Maven
    uses: ./.github/workflows/maven.yaml
    with:
        maven-goal: package
    needs: security


