name: Maven

on:
  workflow_call:
    inputs:
      maven-goal:
        description: 'Maven goal to run'
        required: true
        default: 'package'
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{ "id":"github-publish", "configuration": { "httpHeaders": { "property": { "name":"Authorization", "value":"Bearer ${{ secrets.GITHUB_TOKEN }}"} } } } ]'

      - run: mvn -B ${{ inputs.maven-goal }}